version: '3.9'
services:
  mysql.coinshop.knowledegeuniverse.com:
      container_name: "mysql.coinshop.knowledegeuniverse.com"
      hostname: 'mysql.coinshop.knowledegeuniverse.com'
      image: mysql # You can pull your own customized docker mysql image from your gitlab.
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${RPSWD}
        MYSQL_USER: ${USER}
        MYSQL_PASSWORD: ${UPSWD}
        MYSQL_DATABASE: ${DB}
      volumes:  
        - '~/WebApps/Data/DataBase/coinshop.knowledegeuniverse.com/Mysql/:/var/lib/mysql'

  adminer.coinshop.knowledegeuniverse.com:
      container_name: "adminer.coinshop.knowledegeuniverse.com"
      hostname: 'adminer.coinshop.knowledegeuniverse.com'
      image: adminer
      restart: always
      ports:
        - 8301:8080   
    
  coinshop.knowledegeuniverse.com:
      container_name: "coinshop.knowledegeuniverse.com"
      hostname: 'coinshop.knowledegeuniverse.com'
      build: '.'
      restart: always
      ports:
        - '8300:80'
        
      volumes:
        - '../coinshop.knowledegeuniverse.com/htdocs/:/var/www/html/'   
        - '../coinshop.knowledegeuniverse.com/config/config.json:/var/www/config/coinshop.knowledegeuniverse.com_config/config.json'
