# This docker yml configration is for only server

version: '3.9'
services:
  mysql.lms-erp.com:
      container_name: "mysql.lms-erp.com"
      hostname: 'mysql.lms-erp.com'
      image: mysql # You can pull your own customized docker mysql image from your gitlab.
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${RPSWD}
        MYSQL_USER: ${USER}
        MYSQL_PASSWORD: ${UPSWD}
        MYSQL_DATABASE: ${DB}
      volumes:  
        - '/home/data/lms-erp/mysql:/var/lib/mysql'  # perserve location will be decide after hosting this project

  adminer.lms-erp.com:
      container_name: "adminer.lms-erp.com"
      hostname: 'adminer.lms-erp.com'
      image: adminer
      restart: always
      ports:
        - 8001:8080   
    
  lms-erp.com:
      container_name: "lms-erp.com"
      hostname: 'lms-erp.com'
      build: './lms-erp.com/.'
      restart: always
      ports:
        - '8000:80'
      volumes:
        - './lms-erp.com/lms-erp.com/htdocs/:/var/www/html/'   
        - '/home/data/lms-erp/apache2/apache2/php.ini:/etc/php/8.1/apache2/php.ini'
        - '/home/data/lms-erp/apache2/cli/php.ini:/etc/php/8.1/cli/php.ini'
        - '/home/data/lms-erp/config/config.json:/var/www/config.json'