version: '3.9'
services:
  erp.erp.knowledegeuniverse.com:
      container_name: "mysql.erp.knowledegeuniverse.com"
      hostname: 'mysql.erp.knowledegeuniverse.com'
      image: mysql # You can pull your own customized docker mysql image from your gitlab.
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: ${RPSWD}
        MYSQL_USER: ${USER}
        MYSQL_PASSWORD: ${UPSWD}
        MYSQL_DATABASE: ${DB}
      volumes:  
        - '~/WebApps/Data/DataBase/erp.knowledegeuniverse.com/Mysql/:/var/lib/mysql'

  adminer.erp.knowledegeuniverse.com:
      container_name: "adminer.erp.knowledegeuniverse.com"
      hostname: 'adminer.erp.knowledegeuniverse.com'
      image: adminer
      restart: always
      ports:
        - 8601:8080   
    
  erp.knowledegeuniverse.com:
      container_name: "erp.knowledegeuniverse.com"
      hostname: 'erp.knowledegeuniverse.com'
      build: '.'
      restart: always
      ports:
        - '8600:80'
        
      volumes:
        - '../erp.knowledegeuniverse.com/htdocs/:/var/www/html/'   
        - '../erp.knowledegeuniverse.com/config/config.json:/var/www/config/erp.knowledegeuniverse.com_config/config.json'
